### ISSUE TITLE
Issue generating populate_sdk_ext on Yoe

### ISSUE THREAD

**Issue by wouterlucas** [YoeDistro/yoe-distro#85]
I'm not sure if this is Yoe specific or not, but I'd guess I'll start here and please redirect me if I need to take the issue elsewhere.

I tried creating an extensible SDK to ship to a colleague, however that fails on the final steps for Yoe with the error message below. Tried both a custom image and the error below is with a core-image-base to avoid anything that I'm adding on top of Yoe.

```
ERROR: Execution of event handler 'uninative_event_fetchloader' failed
Traceback (most recent call last):
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/meta/classes/uninative.bbclass", line 86, in uninative_event_fetchloader(e=<bb.event.BuildStarted object at 0x7fee8cae1dd8>):
             glibcver = subprocess.check_output(["ldd", "--version"]).decode('utf-8').split('\n')[0].split()[-1]
    >        if bb.utils.vercmp_string(d.getVar("UNINATIVE_MAXGLIBCVERSION"), glibcver) < 0:
                 raise RuntimeError("Your host glibc verson (%s) is newer than that in uninative (%s). Disabling uninative so that sstate is not corrupted." % (glibcver, d.getVar("UNINATIVE_MAXGLIBCVERSION")))
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/utils.py", line 141, in vercmp_string(a=None, b='2.24'):
     def vercmp_string(a, b):
    >    ta = split_version(a)
         tb = split_version(b)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/utils.py", line 94, in split_version(s=None):
         """Split a version string into its constituent parts (PE, PV, PR)"""
    >    s = s.strip(" <>=")
         e = 0
AttributeError: 'NoneType' object has no attribute 'strip'

ERROR: Command execution failed: Traceback (most recent call last):
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/command.py", line 116, in runAsyncCommand
    commandmethod(self.cmds_async, self, options)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/command.py", line 608, in buildTargets
    command.cooker.buildTargets(pkgs_to_build, task)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/cooker.py", line 1460, in buildTargets
    bb.event.fire(bb.event.BuildStarted(buildname, ntargets), self.databuilder.mcdata[mc])
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/event.py", line 225, in fire
    fire_class_handlers(event, d)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/event.py", line 134, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/event.py", line 106, in execute_handler
    ret = handler(event)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/meta/classes/uninative.bbclass", line 86, in uninative_event_fetchloader
    if bb.utils.vercmp_string(d.getVar("UNINATIVE_MAXGLIBCVERSION"), glibcver) < 0:
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/utils.py", line 141, in vercmp_string
    ta = split_version(a)
  File "/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/bitbake/lib/bb/utils.py", line 94, in split_version
    s = s.strip(" <>=")
AttributeError: 'NoneType' object has no attribute 'strip'


Summary: There were 59 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
ERROR: core-image-base-1.0-r0 do_populate_sdk_ext: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:copy_buildsystem(d)
     0003:
File: '/home/wouter/workspace/rpi/yoe-distro/sources/openembedded-core/meta/classes/populate_sdk_ext.bbclass', lineno: 415, function: copy_buildsystem
     0411:    sdk_ext_type = d.getVar('SDK_EXT_TYPE')
     0412:    if sdk_ext_type != 'minimal' or sdk_include_toolchain or derivative:
     0413:        # Create the filtered task list used to generate the sstate cache shipped with the SDK
     0414:        tasklistfn = d.getVar('WORKDIR') + '/tasklist.txt'
 *** 0415:        create_filtered_tasklist(d, baseoutpath, tasklistfn, conf_initpath)
     0416:    else:
     0417:        tasklistfn = None
     0418:
     0419:    # Add packagedata if enabled
File: '/home/wouter/workspace/rpi/yoe-distro/sources/openembedded-core/meta/classes/populate_sdk_ext.bbclass', lineno: 179, function: create_filtered_tasklist
     0175:        # Clean out residue of running bitbake, which check_sstate_task_list()
     0176:        # will effectively do
     0177:        clean_esdk_builddir(d, sdkbasepath)
     0178:    finally:
 *** 0179:        os.replace(sdkbasepath + '/conf/local.conf.bak', sdkbasepath + '/conf/local.conf')
     0180:
     0181:python copy_buildsystem () {
     0182:    import re
     0183:    import shutil
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image//usr/local/oecore-x86_64/conf/local.conf.bak' -> '/home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/sdk-ext/image//usr/local/oecore-x86_64/conf/local.conf'

ERROR: core-image-base-1.0-r0 do_populate_sdk_ext: Function failed: copy_buildsystem
ERROR: Logfile of failure stored in: /home/wouter/workspace/rpi/yoe-distro/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-base/1.0-r0/temp/log.do_populate_sdk_ext.52043
ERROR: Task (/home/wouter/workspace/rpi/yoe-distro/sources/openembedded-core/meta/recipes-core/images/core-image-base.bb:do_populate_sdk_ext) failed with exit code '1'
```

**Comment by kraj** [comment]
Can you create an empty local.conf file in top level conf folder and see if it helps

**Comment by wouterlucas** [comment]
Same error with an empty local.conf

**Comment by kraj** [comment]
OK are you using docker ? if yes may be disable docker and see if it still happens ?
just trying to narrow it down.

**Comment by wouterlucas** [comment]
Nope, this is a non docker build

**Comment by kraj** [comment]
OK let me try to reproduce it here with `yoe-simple-image`

**Comment by kraj** [comment]
@wouterlucas this should be fixed once oe-core change http://git.openembedded.org/openembedded-core/commit/?h=master-next&id=c0a22d4f81caf615b348fce154072b95d1144128

lands into master and we update the sublayers

you can checkout yoe/mut branch of super repo if you want to try it in meanwhile and see if issue is fixed for you.

**Comment by wouterlucas** [comment]
Yep! Works perfectly with that oe-core commit included. I tried yoe/mut but ran into other problems so decided to only upgrade sources/openembedded-core to master-next and that worked like a charm.

Thanks @kraj !

**Comment by kraj** [comment]
The concerned changes in OE-Core are now upstream
https://github.com/openembedded/openembedded-core/commit/95659bed3f6f3216b346f70cfc9ffae9788c0fc1
